### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by 0xN1nja** [leonardtng/ape-wallpapers#1]
Tried with #4808, doesn't work anymore. Is the project discontinued?

**Comment by leonardtng** [comment]
Try again, IPFS issue should be fixed

**Comment by leonardtng** [comment]
Try again, issue with IPFS should be fixed


<img width="989" alt="Screenshot 2024-08-01 at 00 17 58" src="https://github.com/user-attachments/assets/66ca3389-ef58-4694-b5bb-d158af916107">

**Comment by 0xN1nja** [comment]
Didn't work

**Comment by leonardtng** [comment]
Refresh and try

**Comment by 0xN1nja** [comment]
Working now. Thanks!
